export const SELECTED_QUESTION = "SELECTED_QUESTION";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const UPDATE_QUESTION_INDEX = "UPDATE_QUESTION_INDEX";
export const GET_QUESTIONS = "GET_QUESTIONS";